# fly.toml app configuration file generated for mc-eaglercraft on 2025-04-26T21:42:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mc-eaglercraft'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
