app = "mc-bungee" 
primary_region = "lon"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8081 
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.ports]]
    port = 8081
    protocol = "tcp"